server:
  port: 8081
spring:
  application:
    name: gbnAdmin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goodbuynet
    username: root
    password: Liutong880818@163.com
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  redis:
    host: 127.0.0.1
    database: 1
    port: 6379
    timeout: 3000

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10010/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml