server:
  port: 8082
  #port: 8083
spring:
  application:
    name: transverseNavProvider
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/goodbuynet
    username: root
    password: Liutong880818@163.com
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    timeout: 3000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10010/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.java.pojo